### ISSUE TITLE
Wrong home page

### ISSUE THREAD

**Issue by boh717** [nixentric/Lowkey-Hugo-Theme#2]
Hello,
when I follow your guidelines to install the theme I get the wrong home page:

<img width="790" alt="image" src="https://user-images.githubusercontent.com/3520636/231828073-85e3231b-a985-43ac-9237-27c165649059.png">

Instead from the demo app, it should be like this:

<img width="769" alt="image" src="https://user-images.githubusercontent.com/3520636/231828146-2335d05c-683b-46b5-9f3c-a545432616ab.png">

It's referring to the wrong layout, but I'm not a Hugo expert so I cannot find the bug.

Could you please help me?

**Comment by boh717** [comment]
I can see from your website the same issue: https://nixentric.com/

Is the demo app aligned to the sources?

**Comment by nixentric** [comment]
Hi, thank you for your feedback. 

Actually, I didn't like the single page on the homepage, so I decided to make the homepage as list page. 

But thanks to you, I realized it's not such a bad idea after all, so I added the feature back (you can see the update in the code). 

And now, I have added a feature to select between single page or list page on the homepage (you can specify it in the config/params.toml file)

```
# Homepage Config
isSinglePage = true
```

**Comment by boh717** [comment]
Thanks 😄 
I'm closing the issue then!
