### ISSUE TITLE
How to change my avatar.

### ISSUE THREAD

**Issue by starrliu** [nixentric/Lowkey-Hugo-Theme#24]
I found that the avatar configuration is in `params.toml`:

```
avatar = "/img/profile-picture.jpg"
```

But I cannot find the path to `/img/profile-picture.jpg`, so I don't know how to change the avatar.

Thanks.

**Comment by bijancot** [comment]
hi, did you try take a look at assets folder ? i believe the file should be there

**Comment by starrliu** [comment]
Yes. You are right! Thank u for your help.

**Comment by starrliu** [comment]
Yes. You are right! Thank u for your help.
