### ISSUE TITLE
Sorry to bother you

### ISSUE THREAD

**Issue by treasunew** [nixentric/Lowkey-Hugo-Theme#9]
What is the reason why the images I inserted did not work when using your theme, like this one:
![image](https://github.com/nixentric/Lowkey-Hugo-Theme/assets/104483693/848545b8-78e1-4b92-9494-9040dbb4cd06)
![image](https://github.com/nixentric/Lowkey-Hugo-Theme/assets/104483693/0da54bbb-13e3-48c6-8c5e-71467cead898)

I looked at your post and used the same syntax but it threw an error
![image](https://github.com/nixentric/Lowkey-Hugo-Theme/assets/104483693/ad93e7bf-ca53-43d7-a566-00cc2575f032)
![image](https://github.com/nixentric/Lowkey-Hugo-Theme/assets/104483693/db58f436-2ace-4938-b9de-75953010a4bc)
![image](https://github.com/nixentric/Lowkey-Hugo-Theme/assets/104483693/95d3e716-cfd7-4afd-b21e-e1814abfaa7a)
![image](https://github.com/nixentric/Lowkey-Hugo-Theme/assets/104483693/3471cb17-f6cf-4bd8-912a-5fd0afbcbb0e)

**Comment by nixentric** [comment]
can you share your image file?

**Comment by treasunew** [comment]
yes,  i'm using Hugo Extended Version
![header](https://github.com/nixentric/Lowkey-Hugo-Theme/assets/104483693/93d806a6-90e5-44c0-9193-0cb3ecd54e07)
the original url : http://gd-hbimg.huaban.com/ba964987def008e18f66b3bf89d73a6b94fc8532144c7f-yDphSc

**Comment by treasunew** [comment]
> can you share your image (.jpg) file?
> 
> & are you using Hugo Extended Version? or not?

yes,  i'm using Hugo Extended Version
![header](https://github.com/nixentric/Lowkey-Hugo-Theme/assets/104483693/93d806a6-90e5-44c0-9193-0cb3ecd54e07)
the original url : http://gd-hbimg.huaban.com/ba964987def008e18f66b3bf89d73a6b94fc8532144c7f-yDphSc

**Comment by nixentric** [comment]
It seems the issue is your .md file.

The file:

B:\Coding\Hugowebsite\blog\content\posts\瞒折腾\**随折腾 .md**

Should be in this format:

B:\Coding\Hugowebsite\blog\content\posts\瞒折腾\**index.md**

Please give it a try! 😃

**Comment by treasunew** [comment]
> It seems the issue is your .md file.
> 
> The file:
> 
> B:\Coding\Hugowebsite\blog\content\posts\瞒折腾\ `随折腾.md`
> 
> Should be in this format:
> 
> B:\Coding\Hugowebsite\blog\content\posts\瞒折腾\ `index.md`
> 
> Please give it a try! 😃

thank you so much, i'll try it

**Comment by nixentric** [comment]
Sure, let me know if you're still facing any issues or if you've succeeded

**Comment by treasunew** [comment]
yes, it works. thank you sho much
btw, can't i use HTML tags?

**Comment by treasunew** [comment]
> Sure, let me know if you're still facing any issues or if you've succeeded

yes, it works. thank you sho much
btw, can't i use HTML tags?

**Comment by treasunew** [comment]
> > Sure, let me know if you're still facing any issues or if you've succeeded
> 
> yes, it works. thank you sho much btw, can't i use HTML tags?

sorry, i got it , thank you so much

**Comment by nixentric** [comment]
To insert HTML into Markdown in Hugo, you need to create a new shortcode:

You can read about it here:
https://anaulin.org/blog/hugo-raw-html-shortcode/

**Comment by treasunew** [comment]
> To insert HTML into Markdown in Hugo, you need to create a new shortcode:
> 
> You can read about it here: https://anaulin.org/blog/hugo-raw-html-shortcode/


> To insert HTML into Markdown in Hugo, you need to create a new shortcode:
> 
> You can read about it here: https://anaulin.org/blog/hugo-raw-html-shortcode/

Thank you for your generous guidance.

**Comment by nixentric** [comment]
You're welcome. It was my pleasure. 😄
